### ISSUE TITLE
scrollToItemAtIndexPath:

### ISSUE THREAD

**Issue by maxk11** [awdigital/AWCollectionViewDialLayout#1]
First, I really love this layout; awesome work!

I think I found a bug: I just can't scroll to a specific item programmatically using [self.collectionView scrollToItemAtIndex:[NSIndexPath indexPathForItem:item inSection:0]]; 

Maybe you can take a look at this behavior.

Could you also show some instructions on how to make the items "snap" to the nearest item, so there's always one item "selected"?

**Comment by awdigital** [comment]
Hi, I updated the Control. To scroll to item at IndexPath just use the following code

```
//cell_height  is the height you used to initialize your collectionviewlayout
[self.collectionView setContentOffset:CGPointMake(0, cell_height * item) animated:YES];
```
