### ISSUE TITLE
is it possible to make text horizontal?

### ISSUE THREAD

**Issue by harryyuanfeng** [awdigital/AWCollectionViewDialLayout#10]
Hi, 

Is it possible to make all text/uilabel horizontal?

we have a design need to be like this,

http://ac-3b5q4r6a.clouddn.com/29f9a988f84037a84b8a.jpg

thanks

**Comment by awdigital** [comment]
Hi, 
At the moment this Layout rotate the complete cell. If you want to achieve this effect and only position the cells in a circle without rotating them, you'll have to edit the  "AWCollectionViewDialLayout.m" file.

Add the end of the method `- (UICollectionViewLayoutAttributes *)layoutAttributesForItemAtIndexPath:(NSIndexPath *)indexPath` add the following line

`rotationT = CGAffineTransformMakeRotation(0);`

right before `theAttributes.transform = CGAffineTransformConcat(scaleT, CGAffineTransformConcat(translationT, rotationT));`
