### ISSUE TITLE
How can I scroll by horizontal?

### ISSUE THREAD

**Issue by ali0201** [awdigital/AWCollectionViewDialLayout#4]
thx

**Comment by awdigital** [comment]
Unfortunately Horizontal Scrolliing is not enabled at the moment.

**Comment by rinat-enikeev** [comment]
Hi @ali0201. Yo may find this helpful: 
http://stackoverflow.com/questions/32309704/circular-wheel-animation-implementation-in-ios

Check the gifs in the first answer.
