### ISSUE TITLE
Adding new items causes crash

### ISSUE THREAD

**Issue by DrBeak1** [awdigital/AWCollectionViewDialLayout#5]
When I try to add items I keep getting this error:

> request for number of items in section 0 when there are only 0 sections in the collection view

crashing on line 50 of AWCollectionViewDialLayout.m

This could be due to (a) I load data in from server then reloadData, (b) I have multiple sections.

**Comment by DrBeak1** [comment]
fixed with:

```
-(NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView
{
    NSInteger count = self.items.count;
    return (count == 0) ? 1 : count;
}
```

**Comment by awdigital** [comment]
Hey, thank for your comment. This issue should be fixed now.

**Comment by Akhil-ios** [comment]
Can we have multiple sections here
