### ISSUE TITLE
Right Dial

### ISSUE THREAD

**Issue by JasonTech** [awdigital/AWCollectionViewDialLayout#6]
I'm trying to find a way to have the same display but with the items coming in from the right of the screen instead of left. Any idea how I might be able to do this?
Here's an image to show you what I'm talking about:

![screen shot 2016-05-25 at 15 16 42](https://cloud.githubusercontent.com/assets/1824619/15543249/0eee9090-228c-11e6-86cd-5a5fff6f6f66.png)

**Comment by awdigital** [comment]
Hi Jason. I uploaded a new version of the Layout. Just use the "flip" option to have your items coming from the right side of the screen.

```Objective-C
[dialLayout setShoulFlip:YES];
```

**Comment by JasonTech** [comment]
It's insanely easy to use! Thank you very much!!! 👍
