### ISSUE TITLE
AngularSpacing

### ISSUE THREAD

**Issue by pjebs** [awdigital/AWCollectionViewDialLayout#8]
@awdigital 

I was wondering how to interpret AngularSpacing property.

Obviously the `angularSpacing` is in degrees. Is it in relation to a full circle being 360 degrees or a full circle being 180 degrees.

i.e. Physical angle spacing = 2 * virtual angle spacing, where `angularSpacing` variable represents virtual spacing

If I have 3 items, and I want them to be evenly divided in the full circle, should `angularSpacing` be `360/3` or `180/3`?

**Comment by awdigital** [comment]
Hi,

Correct. basically the angular spacing is 360° divided by the number of items in the circle.
